# Generated by Django 6.0.4 on 2026-04-27 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_major_hub', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='densityreport',
            name='bus_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tracker.busline'),
        ),
        migrations.AddField(
            model_name='busline',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='bus_lines', to='tracker.busstop'),
        ),
        migrations.AddField(
            model_name='densityreport',
            name='bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tracker.busstop'),
        ),
        migrations.AddIndex(
            model_name='densityreport',
            index=models.Index(fields=['bus_line', 'bus_stop'], name='tracker_den_bus_lin_753a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='densityreport',
            index=models.Index(fields=['reported_at'], name='tracker_den_reporte_30454b_idx'),
        ),
    ]
