# Generated by Django 6.0.4 on 2026-04-27 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_busstop_alter_densityreport_bus_line_busline_stops_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='densityreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_shadowbanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='densityreport',
            index=models.Index(fields=['is_active'], name='tracker_den_is_acti_0278d9_idx'),
        ),
    ]
